### ISSUE TITLE
Outdated usage instructions in README

### ISSUE THREAD

**Issue by EsGeh** [vaxr/strapi-provider-email-mock#1]
### Problem

The README is out of date.
With the config given as an example in the current README file, will still use the default email provider.

### Solution

As described in the [latest strapi doc](https://docs.strapi.io/dev-docs/providers#configuring-providers), in order for the default provider being replaced, ...

- the `email` key must be wrapped in a `config` object.
- the `provider` field must contain the full provider name `strapi-provider-email-mock` instead of just `mock`. If not, strapi will reject to start with the following error message:

    `Error: Could not load email provider "mock".`

```
module.exports = ({env}) => ({
  config: {  // <--
    email: {
      provider: 'strapi-provider-email-mock' // <--
      providerOptions: {},
      settings: {
        // If set to false, each email sent will be logged to console
        quiet: true,
        defaultFrom: 'strapi@example.com',
        defaultReplyTo: 'strapi@example.com',
      },
    },
  },  // <--
});
```

**Comment by vaxr** [comment]
Thanks so much for your help!

I have updated the README code accordingly and tested it with Strapi v4.10.5.

Schönen Gruß nach Berlin!
